chat-prefix: [MineTinker]
CheckForUpdates: true #Checks for updates on startup
SendUpdateNotificationToOPs: true #If there is an update the server OP get a notification

logging:
  standard: false #logs important player activities with MineTinker
  debug: false #even more information
  metrics: true

chat-messages: true #Will turn off command output
actionbar-messages: true

LevelStep: 100 #  *(LevelFactor^LevelOfTool)
LevelFactor: 2.0
ResetAtVarOverflow: true #Resets Level and Exp at Integer.MAX_VALUE or Long.MAX_VALUE with 1 and 0. false: no more Exp gain
AddModifierSlotsPerLevel: 1
StartingModifierSlots: 1
ExpPerBlockBreak: 1 #How much XP will the tool get when you break a block
ExpPerEntityHit: 1 #How much XP will the tool get when you hit a Entity with Sword / Bow
ExpPerArrowShot: 1 #How much XP will the tool get when you shoot with the bow
BowExtraExp:
  OnEnderDragonHit: 5 #How much XP will the bow get when you hit the ender dragon
  OnEndCrystalHit: 10 #How much XP will the bow get when you hit a end crystal
  OnWitherHit: 3 #How much XP will the bow get when you hit the wither boss
EnableDamageExp: false #When true: Sword/Bow will gain XP equal to the damage-value
Upgradeable: true #Can you upgrade your tools with an anvil
Repairable: true #Can you repair your tools in your inventory (instead of an anvil) just by dragging the ressource on the tool
AllowEnchanting: false #When enabled you can enchant the tools with vanilla methods (not recommended!)
AllowCrafting: true #Only recommended if used in combination with other Plugins that use the crafting grid for tools. If false: Tools are only aquired with give command
BlockToEnchantModifiers: BOOKSHELF #Block that needs to be right-clicked
HideEnchants: true #Should the vanilla enchantments be hidden on the tool
DurabilityPercentageRepair: 0.34 #How much durability (relative to maximum durability) should the tool recover per item

ItemBehaviour:
  ShowName: true
  SetGlowing: true
  SetInvulnerable: true
  SetPersistent: true
  ForModItems: true

LevelUpEvents:
  enabled: true
  DurabilityRepair: #Repairs the tool
    enabled: true
    percentage: 50
  RandomModifier: #Applies a random modifier
    enabled: true
    percentage: 10
  DropLoot: #Drops specific loot
    enabled: true
    percentage: 25
    minimumDrop: 1
    maximumDrop: 5
    Items:
      - DIAMOND
      - IRON_INGOT
      - GOLD_INGOT
      - EMERALD
  DropXP: #Drops a certain amout of XP
    enabled: true
    percentage: 25
    amount: 100

Sound:
  OnLevelUp: true
  OnCrafting: true
  OnEveryCrafting: false
  OnModding: true
  OnFail: true
  OnEnchanting: true
  OnUpgrade: true
  OnBreaking: true

BannedWorlds: #Worlds where MineTinker-Tools can't be used
  - bannedExample1
  - bannedExample2

Spawners:
  enabled: false #Should be disabled when using a different Spawner plugin
  onlyWithSilkTouch: true
  BannedWorlds: #Worlds where Spawners can't be mined and placed
    - bannedExample1
    - bannedExample2

EasyHarvest:
  enabled: true
  replant: true
  Sound: true
  BannedWorlds: #Worlds where EasyHarvest can't be used
    - bannedExample1
    - bannedExample2
