chat-prefix: [MineTinker]
logging:
  standard: false #logs important player activities with MineTinker
  debug: false #even more information
  metrics: true

chat-messages: true #Will turn off command output
actionbar-messages: true

LevelStep: 100 #  *(LevelFactor^LevelOfTool)
LevelFactor: 2.0
AddModifierSlotsPerLevel: 1
StartingModifierSlots: 1
ExpPerBlockBreak: 1 #How much XP will the tool get when you break a block
ExpPerEntityHit: 1 #How much XP will the tool get when you hit a Entity with Sword / Bow
ExpPerArrowShot: 1 #How much XP will the tool get when you shoot with the bow
EnableDamageExp: false #When true: Sword/Bow will gain XP equal to the damage-value
Upgradeable: true #Can you upgrade your tools with an anvil
Repairable: true #Can you repair your tools in your inventory (instead of an anvil) just by dragging the ressource on the tool
AllowEnchanting: false #When enabled you can enchant the tools with vanilla methods (not recommended!)
AllowCrafting: true #Only recommended if used in combination with other Plugins that use the crafting grid for tools. If false: Tools are only aquired with give command
DurabilityPercentageRepair: 0.34 #How much durability (relative to maximum durability) should the tool recover per item

LevelUpEvents:
  enabled: true
  DurabilityRepair: #Repairs the tool
    enabled: true
    percentage: 50
  RandomModifier: #Applies a random modifier
    enabled: true
    percentage: 10
  DropLoot: #Drops specific loot
    enabled: true
    percentage: 25
    minimumDrop: 1
    maximumDrop: 5
    Items:
      - DIAMOND
      - IRON_INGOT
      - GOLD_INGOT
      - EMERALD
  DropXP: #Drops a certain amout of XP
    enabled: true
    percentage: 25
    amount: 100

Sound:
  OnLevelUp: true
  OnCrafting: true
  OnEveryCrafting: false
  OnModding: true
  OnEnchanting: true
  OnUpgrade: true
  OnBreaking: true

AllowedWorlds: #Worlds where MineTinker-Tools can be used
  - world #default
  - world_nether #default
  - world_the_end #default

AllowedTools: #Here you can disable specific variants of the tools
  Swords:
    - WOODEN_SWORD
    - STONE_SWORD
    - IRON_SWORD
    - GOLDEN_SWORD
    - DIAMOND_SWORD
  Axes:
    - WOODEN_AXE
    - STONE_AXE
    - IRON_AXE
    - GOLDEN_AXE
    - DIAMOND_AXE
  Pickaxes:
    - WOODEN_PICKAXE
    - STONE_PICKAXE
    - IRON_PICKAXE
    - GOLDEN_PICKAXE
    - DIAMOND_PICKAXE
  Shovels:
    - WOODEN_SHOVEL
    - STONE_SHOVEL
    - IRON_SHOVEL
    - GOLDEN_SHOVEL
    - DIAMOND_SHOVEL
  Hoes:
    - WOODEN_HOE
    - STONE_HOE
    - IRON_HOE
    - GOLDEN_HOE
    - DIAMOND_HOE
  Bows:
    - BOW
  Misc:
    - SHIELD

Modifiers:
  Auto-Smelt:
    allowed: true
    name: Auto-Smelt
    name_modifier: Auto-Smelt-Modifier
    MaxLevel: 5
    PercentagePerLevel: 20
    Sound: true
  Beheading:
    allowed: true
    name: Beheading
    name_modifier: Beheading-Modifier
    MaxLevel: 10
    PercentagePerLevel: 10
    EnchantCost: 10
  Directing:
    allowed: true
    name: Directing
    name_modifier: Directing-Modifier
  Ender:
    allowed: true
    name: Ender
    name_modifier: Ender-Modifier
    Sound: true #Sound when teleporting
  Extra-Modifier:
    allowed: true
    name: Extra-Modifier
    ExtraModifierGain: 1
  Fiery:
    allowed: true
    name: Fiery
    name_modifier: Fiery-Modifier
    MaxLevel: 2
    EnchantCost: 10
  Glowing:
    allowed: true
    name: Glowing
    name_modifier: Glowing-Modifier
    Duration: 200 #ticks
  Haste:
    allowed: true
    name: Haste
    name_modifier: Haste-Modifier
    MaxLevel: 5
  Knockback:
    allowed: true
    name: Knockback
    name_modifier: Knockback-Modifier
    MaxLevel: 5
    EnchantCost: 10
  Infinity:
    allowed: true
    name: Infinity
    name_modifier: Infinity-Modifier
    EnchantCost: 10
  Melting:
    allowed: true
    name: Melting
    name_modifier: Melting-Modifier
    MaxLevel: 3
    EnchantCost: 10
    BonusMultiplier: 0.1 #Percent of Bonus-damage per Level
  Luck:
    allowed: true
    name: Luck
    name_modifier: Luck-Modifier
    MaxLevel: 5
  Poisonous:
    allowed: true
    name: Poisonous
    name_modifier: Poisonous-Modifier
    MaxLevel: 5
    EnchantCost: 10
    Duration: 120 #ticks
    DurationMultiplier: 1.1 #Duration * (Multiplier^Level)
    EffectMultiplier: 2 #per Level (Level 1 = 0)
  Power:
    allowed: true
    name: Power
    name_modifier: Power-Modifier
    MaxLevel: 3
    EnchantCost: 10
  Reinforced:
    allowed: true
    name: Reinforced
    name_modifier: Reinforced-Modifier
    MaxLevel: 3
  Self-Repair:
    allowed: true
    name: Self-Repair
    name_modifier: Self-Repair-Modifier
    MaxLevel: 10
    EnchantCost: 10
    PercentagePerLevel: 10
    HealthRepair: 2
  Sharpness:
    allowed: true
    name: Sharpness
    name_modifier: Sharpness-Modifier
    MaxLevel: 5
  Shulking:
    allowed: true
    name: Shulking
    name_modifier: Shulking-Modifier
    MaxLevel: 10
    Duration: 20 #ticks
    EffectMultiplier: 2 #per Level (Level 1 = 0)
  Silk-Touch:
    allowed: true
    name: Silk-Touch
    name_modifier: Silk-Touch-Modifier
    EnchantCost: 10
  Sweeping:
    allowed: true
    name: Sweeping
    name_modifier: Sweeping-Modifier
    MaxLevel: 5
    EnchantCost: 10
  Timber:
    allowed: true
    name: Timber
    name_modifier: Timber-Modifier
  Webbed:
    allowed: true
    name: Webbed
    name_modifier: Webbed-Modifier
    MaxLevel: 3
    Duration: 60 #ticks
    DurationMultiplier: 1.2 #Duration * (Multiplier^Level)
    EffectMultiplier: 2 #per Level (Level 1 = 0)
  XP:
    allowed: true
    name: XP
    MaxLevel: 10
    PercentagePerLevel: 2
    XPAmount: 1 #amount of XP

Spawners:
  enabled: true #Should be disabled when using a different Spawner plugin
  onlyWithSilkTouch: true
  AllowedWorlds: #Worlds where Spawners can be mined and placed
    - world #default
    - world_nether #default
    - world_the_end #default

Elevator:
  enabled: true
  Sound: true #(Chest opening and closing)
  AllowedWorlds: #Worlds where Elevator can be used
  - world #default
  - world_nether #default
  - world_the_end #default

Builderswands:
  enabled: true
  useDurability: true
  AllowedWorlds: #Worlds where MineTinker-Builderswands can be used
  - world #default
  - world_nether #default
  - world_the_end #default

Language:
  #Tool
  Identifier: MineTinker-Tool
  Identifier_Builderswand: MineTinker-Builderswand
  LevelLine: Level #no spaces
  ExpLine: Exp #no spaces
  FreeModifierSlotsLine: Free Modifiers Slots #exactly two spaces for no error
  ModifiersLine: Modifiers
