chat-prefix: [MineTinker]
logging:
  standard: false
  debug: false
  metrics: true

LevelStep: 100
LevelFactor: 2.0
AddModifierSlotsPerLevel: 1
StartingModifierSlots: 1
ExpPerBlockBreak: 1
Upgradeable: true
AllowEnchanting: false
DurabilityPercentageRepair: 0.3

Sound:
  OnLevelUp: true
  OnCrafting: true
  OnEveryCrafting: false
  OnModding: true
  OnEnchanting: true
  OnUpgrade: true
  OnBreaking: true

AllowedTools:
  Swords:
    - WOOD_SWORD
    - STONE_SWORD
    - IRON_SWORD
    - GOLD_SWORD
    - DIAMOND_SWORD
  Axes:
    - WOOD_AXE
    - STONE_AXE
    - IRON_AXE
    - GOLD_AXE
    - DIAMOND_AXE
  Pickaxes:
    - WOOD_PICKAXE
    - STONE_PICKAXE
    - IRON_PICKAXE
    - GOLD_PICKAXE
    - DIAMOND_PICKAXE
  Shovels:
    - WOOD_SPADE
    - STONE_SPADE
    - IRON_SPADE
    - GOLD_SPADE
    - DIAMOND_SPADE
  Hoes:
    - WOOD_HOE
    - STONE_HOE
    - IRON_HOE
    - GOLD_HOE
    - DIAMOND_HOE
  Bows:
    - BOW

Modifiers:
  Auto-Smelt:
    allowed: true
    MaxLevel: 5
    PercentagePerLevel: 20
    Sound: true
  Self-Repair:
    allowed: true
    MaxLevel: 10
    EnchantCost: 10
    PercentagePerLevel: 10
    HealthRepair: 2
  Extra-Modifier:
    allowed: true
    ExtraModifierGain: 1
  Fiery:
    allowed: true
    EnchantCost: 10
  Haste:
    allowed: true
  Power:
    allowed: true
  Reinforced:
    allowed: true
  Sharpness:
    allowed: true
  Luck:
    allowed: true
    allowedOnSword: true
  Silk-Touch:
    allowed: true
    EnchantCost: 10
  XP:
    allowed: true
    MaxLevel: 10
    PercentagePerLevel: 2
    XPAmount: 1
