chat-prefix: [MineTinker]
logging:
  standard: false
  debug: false
  metrics: true

LevelStep: 100
LevelFactor: 2.0
AddModifierSlotsPerLevel: 1
StartingModifierSlots: 1
ExpPerBlockBreak: 1
ExpPerSwordSwing: 1
EnableDamageExp: false
Upgradeable: true
AllowEnchanting: false
DurabilityPercentageRepair: 0.3

Sound:
  OnLevelUp: true
  OnCrafting: true
  OnEveryCrafting: false
  OnModding: true
  OnEnchanting: true
  OnUpgrade: true
  OnBreaking: true

AllowedWorlds:
  - world
  - world_nether
  - world_the_end

AllowedTools:
  Swords:
    - WOODEN_SWORD
    - STONE_SWORD
    - IRON_SWORD
    - GOLDEN_SWORD
    - DIAMOND_SWORD
  Axes:
    - WOODEN_AXE
    - STONE_AXE
    - IRON_AXE
    - GOLDEN_AXE
    - DIAMOND_AXE
  Pickaxes:
    - WOODEN_PICKAXE
    - STONE_PICKAXE
    - IRON_PICKAXE
    - GOLDEN_PICKAXE
    - DIAMOND_PICKAXE
  Shovels:
    - WOODEN_SHOVEL
    - STONE_SHOVEL
    - IRON_SHOVEL
    - GOLDEN_SHOVEL
    - DIAMOND_SHOVEL
  Hoes:
    - WOODEN_HOE
    - STONE_HOE
    - IRON_HOE
    - GOLDEN_HOE
    - DIAMOND_HOE
  Bows:
    - BOW

Modifiers:
  Auto-Smelt:
    allowed: true
    name: Auto-Smelt
    name_modifier: Auto-Smelt-Modifier
    MaxLevel: 5
    PercentagePerLevel: 20
    Sound: true
  Beheading:
    allowed: true
    name: Beheading
    name_modifier: Beheading-Modifier
    MaxLevel: 10
    PercentagePerLevel: 10
    EnchantCost: 10
  Self-Repair:
    allowed: true
    name: Self-Repair
    name_modifier: Self-Repair-Modifier
    MaxLevel: 10
    EnchantCost: 10
    PercentagePerLevel: 10
    HealthRepair: 2
  Extra-Modifier:
    allowed: true
    name: Extra-Modifier
    ExtraModifierGain: 1
  Fiery:
    allowed: true
    name: Fiery
    name_modifier: Fiery-Modifier
    EnchantCost: 10
  Haste:
    allowed: true
    name: Haste
    name_modifier: Haste-Modifier
  Power:
    allowed: true
    name: Power
    name_modifier: Power-Modifier
    EnchantCost: 10
  Reinforced:
    allowed: true
    name: Reinforced
    name_modifier: Reinforced-Modifier
  Sharpness:
    allowed: true
    name: Sharpness
    name_modifier: Sharpness-Modifier
  Luck:
    allowed: true
    name: Luck
    name_modifier: Luck-Modifier
    allowedOnSword: true
  Silk-Touch:
    allowed: true
    name: Silk-Touch
    name_modifier: Silk-Touch-Modifier
    EnchantCost: 10
  XP:
    allowed: true
    name: XP
    MaxLevel: 10
    PercentagePerLevel: 2
    XPAmount: 1

Elevator:
  enabled: true
  Sound: true
  AllowedWorlds:
  - world
  - world_nether
  - world_the_end

Builderswands:
  enabled: true
  useDurability: true
  AllowedWorlds:
  - world
  - world_nether
  - world_the_end