chat-prefix: [MineTinker]
logging:
  standard: false
  debug: false
  metrics: true

LevelStep: 100
LevelFactor: 2.0
AddModifierSlotsPerLevel: 1
StartingModifierSlots: 1
ExpPerBlockBreak: 1
ExpPerSwordSwing: 1
EnableDamageExp: false
Upgradeable: true
AllowEnchanting: false
DurabilityPercentageRepair: 0.3

Sound:
  OnLevelUp: true
  OnCrafting: true
  OnEveryCrafting: false
  OnModding: true
  OnEnchanting: true
  OnUpgrade: true
  OnBreaking: true

AllowedTools:
  Swords:
    - WOODEN_SWORD
    - STONE_SWORD
    - IRON_SWORD
    - GOLDEN_SWORD
    - DIAMOND_SWORD
  Axes:
    - WOODEN_AXE
    - STONE_AXE
    - IRON_AXE
    - GOLDEN_AXE
    - DIAMOND_AXE
  Pickaxes:
    - WOODEN_PICKAXE
    - STONE_PICKAXE
    - IRON_PICKAXE
    - GOLDEN_PICKAXE
    - DIAMOND_PICKAXE
  Shovels:
    - WOODEN_SHOVEL
    - STONE_SHOVEL
    - IRON_SHOVEL
    - GOLDEN_SHOVEL
    - DIAMOND_SHOVEL
  Hoes:
    - WOODEN_HOE
    - STONE_HOE
    - IRON_HOE
    - GOLDEN_HOE
    - DIAMOND_HOE
  Bows:
    - BOW

Modifiers:
  Auto-Smelt:
    allowed: true
    MaxLevel: 5
    PercentagePerLevel: 20
    Sound: true
  Self-Repair:
    allowed: true
    MaxLevel: 10
    EnchantCost: 10
    PercentagePerLevel: 10
    HealthRepair: 2
  Extra-Modifier:
    allowed: true
    ExtraModifierGain: 1
  Fiery:
    allowed: true
    EnchantCost: 10
  Haste:
    allowed: true
  Power:
    allowed: true
    EnchantCost: 10
  Reinforced:
    allowed: true
  Sharpness:
    allowed: true
  Luck:
    allowed: true
    allowedOnSword: true
  Silk-Touch:
    allowed: true
    EnchantCost: 10
  XP:
    allowed: true
    MaxLevel: 10
    PercentagePerLevel: 2
    XPAmount: 1

Elevator:
  enabled: true
  Sound: true